id: P006610
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16654
  title: རྒྱ་བོད་ཤན་སྦྱར་ཚོན་ཁྲ་ཅན་གྱི་རོ་བཀྲའི་དཔེ་རིས་མཐོང་བ་དོན་གསལ།
  author: ''
  volumes:
    034aaabb4e8145faa234fe210446656f:
      image_group_id: I2PD17774
      title: ''
      volume_number: 1
      total_pages: 284
      base_file: v001.txt
